name = "Bigleaf"
uuid = "e2ae9153-b66f-47c5-85f1-c6d65380123f"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "0.3.1-DEV"

[deps]
AstroLib = "c7932e45-9af1-51e7-9da9-f004cd3a462b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
AstroLib = "0.4.1"
DataFrames = "1.2.2"
FillArrays = "0.12.7, 0.13"
Infiltrator = "1"
LabelledArrays = "1.6.5"
Missings = "1.0.2"
Optim = "1.4.1"
PaddedViews = "0.5.10"
Parameters = "0.12.3"
Pipe = "1.3"
RecursiveArrayTools = "2.20.0"
StaticArrays = "1.2.13"
StatsBase = "0.33.12"
Suppressor = "0.2"
Tables = "1.6.0"
TimeZones = "1.6.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
